### CALENDAR
GET http://localhost:3000/calendar/2026-09-09

### PARISHES
GET http://localhost:3000/parish/paris

### SYNAXAR
GET http://localhost:3000/synaxar

### VITA
GET http://localhost:3000/vita/21

### READING
GET http://localhost:3000/reading/872

### NEWS
GET http://localhost:3000/news

### NEWS DETAIL
GET http://localhost:3000/news/8

### PRIVACY
GET http://localhost:3000/privacy

### MAP
GET http://localhost:3000/map-data

### IMAGES
GET http://localhost:3000/images/ecof-yellow.png