### CALENDAR
GET localhost:3000/calendar/2026-07-30

### PARISHES
GET localhost:3000/parish/poitiers

### SYNAXAR
GET localhost:3000/synaxar

### VITA
GET localhost:3000/vita/1478

### READING
GET localhost:3000/reading/872

### NEWS
GET localhost:3000/news

### NEWS DETAIL
GET localhost:3000/news/8

### PRIVACY
GET localhost:3000/privacy

### MAP
GET localhost:3000/map-data

### IMAGES
GET localhost:3000/images/ecof-yellow.png